# Generated by Django 4.2.5 on 2023-09-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_category_alter_package_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Country',
        ),
    ]
