# Generated by Django 4.2.5 on 2023-09-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_rename_category_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tour.country'),
        ),
    ]
