# Generated by Django 4.2.5 on 2023-09-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0007_remove_customer_date_joined_remove_customer_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='static/package_images/'),
        ),
    ]
