# Generated by Django 4.2.5 on 2023-09-20 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0010_alter_customer_profile_picture_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='package',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
