# Generated by Django 4.2.5 on 2023-09-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0011_package_end_date_package_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='start_date',
        ),
    ]
