# Generated by Django 4.2.5 on 2023-09-20 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0012_remove_package_end_date_remove_package_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='booking_period',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
