# Generated by Django 4.2.5 on 2023-09-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0013_package_booking_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='booking_period',
        ),
    ]
