# Generated by Django 4.2.5 on 2023-09-20 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0014_remove_package_booking_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.package')),
            ],
        ),
    ]
