# Generated by Django 4.2.5 on 2023-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0016_booking_address_booking_email_booking_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=10),
        ),
    ]
