# Generated by Django 4.2.5 on 2023-09-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0018_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_Us',
        ),
    ]
