# Generated by Django 4.2.5 on 2023-09-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0019_rename_contact_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Country',
            new_name='country',
        ),
        migrations.AddField(
            model_name='package',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
