# Generated by Django 4.2.5 on 2023-09-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0020_rename_country_package_country_package_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
