# Generated by Django 4.2.5 on 2023-09-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0023_remove_payment_customer_name_remove_payment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
